# Generated by Django 5.1.4 on 2024-12-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_master_video_url_master_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/services/'),
        ),
    ]
