# Generated by Django 5.1.4 on 2024-12-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_service_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField()),
            ],
        ),
    ]
